### ISSUE TITLE
Dashboard is a blank page in Browser

### ISSUE THREAD

**Issue by EL-S** [jaruba/PowderWeb#41]
I extracted the files from the zip, ran the GUI through the EXE and set the allowed user to 1. I then opened the Dashboard in the browser, registered a user and after logging in there is a blank page. In the DevTools console there is an error,

> TypeError: Argument 1 of ResizeObserver.observe does not implement interface Element.

 the error is also worded as the following in some browsers,

> TypeError: Failed to execute 'observe' on 'ResizeObserver': parameter 1 is not of type 'Element'.

I tested it with Brave, Chrome, Microsoft Edge Chromium, Chrome Android and Firefox on Windows 10. However, the built-in Powder Web browser appears to work fine.

![image](https://user-images.githubusercontent.com/31227083/78436321-5204ca00-76c2-11ea-8451-b5369fb88a7c.png)
![image](https://user-images.githubusercontent.com/31227083/78436355-54672400-76c2-11ea-9914-f404a62057a4.png)
![image](https://user-images.githubusercontent.com/31227083/78436402-57621480-76c2-11ea-8a2d-0370e4c423a8.png)

**Comment by jaruba** [comment]
thank u for reporting

**Comment by jaruba** [comment]
I've found a workaround for this: https://github.com/jaruba/PowderWeb/commit/52f77123922cd22c25aa0e76f3011b4c9de51e2c

But I'm really unsure of when I'll be able to release this change as I don't have all my gear with me and my country is in lockdown..

**Comment by jaruba** [comment]
You could also make this change yourself in the meanwhile, by editing `/resources/app/dist/videojs-7.0.3.js`.

I've also noticed another bug with newer Chrome versions, which don't show the progress of the download in plain text, that could also be fixed with this change: https://github.com/jaruba/PowderWeb/commit/0e6e39f12a77268d46a631073906ce3d9e61cc81

**Comment by jaruba** [comment]
Other then that, the app seems to work as expected with newer browser versions.. (as far as i can tell, at least)

**Comment by EL-S** [comment]
Thanks! I made both changes and everything is immediately working perfectly now :) Hopefully anyone else that has this problem sees this issue until you get access to your gear.

**Comment by jaruba** [comment]
this was fixed in the latest release
