### ISSUE TITLE
Error occurred while trying to proxy request

### ISSUE THREAD

**Issue by cddharthsingh** [jaruba/PowderWeb#62]
@jaruba 
After running 
`npm run start`
the server starts at port 3000
but when I try to do anything for example logging in it shows up error saying - Error occured while trying to proxy request.
![image](https://user-images.githubusercontent.com/31313139/97780469-deb92d00-1baa-11eb-9eeb-c78b139d8d5f.png)

**Comment by odmivolsi** [comment]
@jaruba same issue

**Comment by jaruba** [comment]
Try using `npm run start-back` in one terminal window, and `npm run start-front` in another. As far as I can tell the backend is not running in ur setup.

**Comment by jaruba** [comment]
U might need to use `npm run build-front` before those, if u have not already.

**Comment by cddharthsingh** [comment]
hey @jaruba I have tried all these commands.
when I run `npm run start-back`
first, this shows up : 
![image](https://user-images.githubusercontent.com/31313139/97781026-926fec00-1bae-11eb-8e9e-eebcbcb88a17.png)
and after this it hangs at this: 
![image](https://user-images.githubusercontent.com/31313139/97781036-9f8cdb00-1bae-11eb-8ecc-1b7cfd2f075f.png)

**Comment by cddharthsingh** [comment]
Front end is working fine!

**Comment by jaruba** [comment]
That error says that the `youtube-dl` module failed to install during `npm install`

**Comment by cddharthsingh** [comment]
Yeah i could see that. Can you guide me how to fix it

**Comment by jaruba** [comment]
What error do you get when you do `npm install`? That's where the issue is.

**Comment by jaruba** [comment]
It might also be possible that `youtube-dl` failed installing because you're not using the recommended Node.js and NPM versions from the readme:
> This project was built with Node v8.12.0 and NPM v6.4.1

**Comment by odmivolsi** [comment]
@jaruba i just read that YouTube-dl has been removed by github a week back, is that whats causing the issue?

**Comment by jaruba** [comment]
I know it was removed from GH, but I can't know if that's the issue unless u delete the `node_modules` folder and show me the error ur getting from `npm install`

**Comment by jaruba** [comment]
I think I fixed the issue with `youtube-dl` not installing correctly, try `npm install` again and if you still have problems you can reopen the issue.
