### ISSUE TITLE
Error while running the application

### ISSUE THREAD

**Issue by yashkhandelwal05** [jaruba/PowderWeb#64]
<img width="419" alt="error" src="https://user-images.githubusercontent.com/68495722/98559896-2e93a480-22cd-11eb-8e0d-20f69bf82036.PNG">

**Comment by jaruba** [comment]
@yashkhandelwal05 can u delete the `node_modules` folder and do `npm install` again, there should be an error when installing the `youtube-dl` module (the error u posted happens when the youtube-dl binary is missing, so it failed installing), paste it here so I can see what's happening.

**Comment by jaruba** [comment]
Closing this in favor of https://github.com/jaruba/PowderWeb/issues/65 , as that's what's causing this.
