### ISSUE TITLE
Error while install node_modules

### ISSUE THREAD

**Issue by yashkhandelwal05** [jaruba/PowderWeb#65]
<img width="713" alt="error1" src="https://user-images.githubusercontent.com/68495722/98560342-ad88dd00-22cd-11eb-9aaf-482a668eca0f.PNG">

**Comment by jaruba** [comment]
Oh, lol, I just noticed the error in this other issue.

**Comment by jaruba** [comment]
I don't get that error, so you probably aren't using the recommended NPM / Node versions from the README:
> Node v8.12.0 and NPM v6.4.1

If you still have problems after using the recommended versions, you can reopen this issue.
