### ISSUE TITLE
Serving locally

### ISSUE THREAD

**Issue by programerr01** [jaruba/PowderWeb#68]
How to serve it locally.
I tried npm start it shows signup page but then 
```bash
(node:48769) TimeoutOverflowWarning: 9007199254740991 does not fit into a 32-bit signed integer.
Timer duration was truncated to 2147483647.

(node:48769) TimeoutOverflowWarning: 9007199254740991 does not fit into a 32-bit signed integer.
Timer duration was truncated to 2147483647.

[HPM] Error occurred while trying to proxy request /actions?method=login&value=%7B%22email%22%3A%a%40gmail.com%22%2C%22password%22%3A%227hBd%3B%2F~8%22%7D from localhost:3000 to http://localhost:11485 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)

(node:48769) TimeoutOverflowWarning: 9007199254740991 does not fit into a 32-bit signed integer.
Timer duration was truncated to 2147483647.

(node:48769) TimeoutOverflowWarning: 9007199254740991 does not fit into a 32-bit signed integer.
Timer duration was truncated to 2147483647.

[HPM] Error occurred while trying to proxy request /actions?method=login&value=%7B%22email%22%3A%a%40gmail.com%22%2C%22password%22%3A%227hBd%3B%2F~8%22%7D from localhost:3000 to http://localhost:11485 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)



```
this shows up

**Comment by jaruba** [comment]
did you get any errors during `npm install`?

try running `npm run start-front` and `npm run start-back` separately in 2 terminals. (instead of doing `npm start`)

the `TimeoutOverflowWarning`s show because you are not using the same NPM and Node versions that the README says you should:

> Node v8.12.0 and NPM v6.4.1

**Comment by vedo18** [comment]
when i am trying to install it is giving me this error :
(current: {"os":"win32","arch":"x64"})

npm ERR! Unexpected end of JSON input while parsing near '...{"name":"async","vers'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\saket shanu\AppData\Roaming\npm-cache\_logs\2020-11-11T09_56_43_702Z-debug.log

**Comment by jaruba** [comment]
@vedo18 are u using the recommended node and npm versions?

> Node v8.12.0 and NPM v6.4.1

If so, delete the `node_modules` folder and do `npm install` again

**Comment by programerr01** [comment]
solved
